/**
 * Application State Machine — valid states and transitions.
 * Only Team C changes authoritative application state.
 */
const APPLICATION_STATES = {
  APPLIED: 'APPLIED',
  SCREENING: 'SCREENING',
  RULE_EVALUATED: 'RULE_EVALUATED',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  SELECTED: 'SELECTED',
  OFFER_ISSUED: 'OFFER_ISSUED',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  WAITLISTED: 'WAITLISTED',
  WITHDRAWN: 'WITHDRAWN',
  EXPIRED: 'EXPIRED',
  COMPENSATION_REQUIRED: 'COMPENSATION_REQUIRED',
};

/** Valid transitions: { FROM_STATE: [TO_STATES...] } */
const VALID_TRANSITIONS = {
  APPLIED: ['SCREENING', 'WITHDRAWN', 'EXPIRED'],
  SCREENING: ['RULE_EVALUATED', 'WITHDRAWN', 'EXPIRED'],
  RULE_EVALUATED: ['SHORTLISTED', 'NOT_ELIGIBLE', 'WAITLISTED', 'WITHDRAWN'],
  SHORTLISTED: ['INTERVIEW_SCHEDULED', 'WAITLISTED', 'WITHDRAWN'],
  INTERVIEW_SCHEDULED: ['SELECTED', 'WAITLISTED', 'WITHDRAWN', 'COMPENSATION_REQUIRED'],
  SELECTED: ['OFFER_ISSUED', 'WITHDRAWN', 'COMPENSATION_REQUIRED'],
  OFFER_ISSUED: [],
  NOT_ELIGIBLE: [],
  WAITLISTED: ['SHORTLISTED', 'WITHDRAWN', 'EXPIRED'],
  WITHDRAWN: [],
  EXPIRED: [],
  COMPENSATION_REQUIRED: ['SCREENING', 'WAITLISTED'],
};

/** Drive operational states */
const DRIVE_STATES = {
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  SCREENING: 'SCREENING',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
};

/** Eligibility decision results (from Team A) */
const ELIGIBILITY_RESULTS = {
  ELIGIBLE: 'ELIGIBLE',
  CONDITIONAL: 'CONDITIONAL',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
};

/** Standard error codes shared across all services */
const ERROR_CODES = {
  // Client errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  RULE_CONFLICT: 'RULE_CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  // Server / integration errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  LOCK_TIMEOUT: 'LOCK_TIMEOUT',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  COMPENSATION_REQUIRED: 'COMPENSATION_REQUIRED',
};

/** API version prefix */
const API_VERSION = 'v1';

module.exports = {
  APPLICATION_STATES,
  VALID_TRANSITIONS,
  DRIVE_STATES,
  ELIGIBILITY_RESULTS,
  ERROR_CODES,
  API_VERSION,
};
